### ISSUE TITLE
unused argument (info = info_list)

### ISSUE THREAD

**Issue by nipnipj** [tidymodels/tidymodels#119] opened 2024-03-22 01:33 UTC
I'm trying to fit a model as follows:
```
xgboost_model <-
  boost_tree( ) %>%
  set_engine("xgboost") %>% 
  set_mode("regression")

wf_xgboost <- workflow() %>% 
  add_recipe(rec) %>% 
  add_model(xgboost_model)

trained_wf <- wf_xgboost %>% fit(train_data)
```
I get the following error:

```
Error in xgboost::xgb.DMatrix(data = x[trn_index, , drop = FALSE], missing = NA,  : 
  unused argument (info = info_list)
```

**Comment by EmilHvitfeldt** [comment] 2024-03-22 02:08
Closing as duplicate of https://github.com/tidymodels/parsnip/issues/1087

**Closed** 2024-03-22 02:08 UTC
